<?php

/** Generated by Latte 3.1.1 */

use Latte\Runtime as LR;

/** source: /var/www/html/app/Presentation/@layout.latte */
final class Template_7663fae574 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<!DOCTYPE html>
<html lang="cs">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>';
		if ($this->hasBlock('title')) /* pos 7:9 */ {
			$this->renderBlock('title', [], function ($s, $type) {
				$ʟ_fi = new LR\FilterInfo($type);
				return LR\Helpers::convertTo($ʟ_fi, 'html', $this->filters->filterContent('stripHtml', $ʟ_fi, $s));
			}) /* pos 7:22 */;
			echo ' | ';
		}
		echo 'Mapa Vysočany</title>

	<style>
		:root {
			font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
			line-height: 1.5;
			color: #222;
		}

		body {
			margin: 0;
			padding: 1.5rem;
			max-width: 1100px;
			margin-inline: auto;
		}

		h1 {
			margin-top: 0;
		}

		.flash {
			padding: 0.75rem 1rem;
			border-radius: 6px;
			margin-bottom: 1rem;
		}

		.flash.info { background: #e8f4fd; }
		.flash.success { background: #e8f8ef; }
		.flash.error { background: #fdecea; }
	</style>

	';
		if ($ʟ_tmp = $this->global->assets->resolve('main.js', [], true)) /* pos 38:2 */ {
			echo $this->global->assets->renderAsset($ʟ_tmp);
		}echo '
</head>

<body>
';
		foreach ($flashes as $flash) /* pos 42:7 */ {
			echo '	<div';
			echo ($ʟ_tmp = array_filter(['flash', $flash->type])) ? ' class="' . LR\HtmlHelpers::escapeAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* pos 42:38 */;
			echo '>';
			echo LR\HtmlHelpers::escapeText($flash->message) /* pos 42:68 */;
			echo '</div>
';

		}

		echo "\n";
		$this->renderBlock('content', [], 'html') /* pos 44:2 */;
		echo '</body>
</html>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['flash' => '42'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
