<?php

/** Generated by Latte 3.1.1 */

use Latte\Runtime as LR;

/** source: /var/www/html/app/Presentation/Home/default.latte */
final class Template_82e7d3d18d extends Latte\Runtime\Template
{
	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('title', get_defined_vars()) /* pos 1:1 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	/** {block title} on line 1 */
	public function blockTitle(array $ʟ_args): void
	{
		echo 'Mapa adres';
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '	<h1>Mapa adres</h1>
	<p class="map-intro">
		Adresní body z OpenStreetMap (okolí Jimramova). Kliknutím na bod zobrazíte detail a odkaz do katastru.
	</p>

	<ul class="map-legend">
		<li><span class="map-legend__dot map-legend__dot--with-owners"></span> evidovaní vlastníci</li>
		<li><span class="map-legend__dot map-legend__dot--no-owners"></span> bez záznamu vlastníků</li>
	</ul>

	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="">

	<style>
		#map {
			height: 600px;
			width: 100%;
			border-radius: 8px;
			border: 1px solid #ddd;
		}

		.map-intro {
			color: #555;
			max-width: 60rem;
		}

		.map-legend {
			display: flex;
			gap: 1.5rem;
			list-style: none;
			padding: 0;
			margin: 0 0 1rem;
		}

		.map-legend__dot {
			display: inline-block;
			width: 12px;
			height: 12px;
			border-radius: 50%;
			margin-right: 0.35rem;
			vertical-align: middle;
		}

		.map-legend__dot--with-owners {
			background: #c0392b;
		}

		.map-legend__dot--no-owners {
			background: #2980b9;
		}
	</style>

	<div id="map"></div>
	<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

	<script>
		const elements = ';
		echo LR\Helpers::escapeJs($mapData) /* pos 59:20 */;
		echo ';
	</script>

	<script>
		const map = L.map(\'map\').setView([49.43, 16.81], 13);

		L.tileLayer(\'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png\', {
			maxZoom: 19,
			attribution: \'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>\',
		}).addTo(map);

		const markers = [];

		elements.forEach((el) => {
			const owners = el.ownersData ?? [];
			const hasOwners = owners.length > 0;

			let ownersHtml = \'\';
			if (hasOwners) {
				ownersHtml = \'<b>Vlastníci:</b><br>\';
				owners.forEach((o) => {
					ownersHtml += `${o.name} – podíl: ${o.share || \'1\'}<br>`;
				});
			}

			const popupContent = `
				<b>${el.place ?? \'\'} ${el.housenumber ?? \'\'}</b><br>
				PSČ: ${el.postcode ?? \'–\'}<br>
				OSM ID: ${el.id}<br>
				<a href="https://nahlizenidokn.cuzk.cz/MapaIdentifikace.aspx?l=KN&x=${el.sjtsk_x}&y=${el.sjtsk_y}" target="_blank" rel="noopener">
					Zobrazit v katastru (KN)
				</a>
				${ownersHtml ? \'<br>\' + ownersHtml : \'\'}
			`;

			const color = hasOwners ? \'#c0392b\' : \'#2980b9\';

			const marker = L.circleMarker([el.lat, el.lon], {
				radius: 8,
				fillColor: color,
				color: color,
				weight: 1,
				opacity: 1,
				fillOpacity: 0.85,
			})
				.addTo(map)
				.bindPopup(popupContent);

			markers.push(marker);
		});

		if (markers.length > 0) {
			const group = L.featureGroup(markers);
			map.fitBounds(group.getBounds().pad(0.1));
		}

		map.invalidateSize();
	</script>
';
	}
}
